Meisi branch
qiqiustb/slack-challenge pull request #1
Opened 2017-02-09 07:07 UTC by huangmeisi

this is a dummy change.

2017-02-09 07:09 UTC, qiqiustb commented on Makefile
> +# change1
this is not right.

2017-02-09 07:09 UTC, qiqiustb commented on README.md
> +Change 2
this is also not right.

2017-02-09 07:10 UTC, huangmeisi commented on README.md
> +Change 2
ok then.

2017-02-10 06:26 UTC, qiqiustb requested changes
I request for a change.

2017-02-10 06:26 UTC, qiqiustb commented on README.md
> +change 3
blabla.

2017-02-10 06:27 UTC, huangmeisi commented on README.md
> +change 3
haode

2017-02-10 06:29 UTC, qiqiustb approved these changes
LGTM

2017-02-10 06:29 UTC, merged